# Generated by Django 5.1.7 on 2025-06-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('address', models.CharField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField()),
                ('landmark', models.CharField()),
                ('alternative_mobile', models.CharField()),
            ],
        ),
    ]
