# Generated by Django 5.2.3 on 2025-06-13 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=20)),
                ('originalPrice', models.IntegerField()),
                ('offerPrice', models.IntegerField()),
                ('availableOffers', models.TextField()),
                ('highlights', models.TextField()),
                ('seller', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
