# Generated by Django 5.2.3 on 2025-06-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Cart_images')),
                ('originalPrice', models.IntegerField()),
                ('offerPrice', models.IntegerField()),
                ('seller', models.CharField(max_length=50)),
            ],
        ),
    ]
