# Generated by Django 5.1.7 on 2025-06-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0005_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('originalPrice', models.IntegerField()),
                ('offerPrice', models.IntegerField()),
                ('image', models.ImageField(upload_to='filters')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
