# Generated by Django 5.1.7 on 2025-06-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0006_filter_product_company_alter_cart_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='orders')),
                ('originalPrice', models.IntegerField()),
                ('offerPrice', models.IntegerField()),
                ('seller', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
