# Generated by Django 5.1.7 on 2025-06-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0008_address_delete_filter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
