# Generated by Django 5.2.6 on 2025-10-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0009_delete_address_delete_cart_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
