# Generated by Django 5.1.7 on 2025-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_shop', '0011_category_product_category_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('JPY', 'Japanese Yen (¥)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('CNY', 'Chinese Yuan (¥)'), ('CHF', 'Swiss Franc (CHF)'), ('KRW', 'South Korean Won (₩)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Złoty (zł)'), ('CZK', 'Czech Koruna (Kč)'), ('HUF', 'Hungarian Forint (Ft)'), ('RUB', 'Russian Ruble (₽)'), ('BRL', 'Brazilian Real (R$)'), ('MXN', 'Mexican Peso ($)'), ('AED', 'UAE Dirham (د.إ)'), ('SAR', 'Saudi Riyal (﷼)'), ('THB', 'Thai Baht (฿)'), ('MYR', 'Malaysian Ringgit (RM)'), ('PHP', 'Philippine Peso (₱)'), ('IDR', 'Indonesian Rupiah (Rp)'), ('VND', 'Vietnamese Dong (₫)'), ('TWD', 'Taiwan Dollar (NT$)'), ('TRY', 'Turkish Lira (₺)'), ('ZAR', 'South African Rand (R)'), ('EGP', 'Egyptian Pound (£)'), ('NGN', 'Nigerian Naira (₦)'), ('KES', 'Kenyan Shilling (KSh)'), ('MAD', 'Moroccan Dirham (MAD)'), ('JOD', 'Jordanian Dinar (JD)'), ('KWD', 'Kuwaiti Dinar (KD)'), ('BHD', 'Bahraini Dinar (BD)'), ('OMR', 'Omani Rial (OMR)'), ('QAR', 'Qatari Riyal (QR)'), ('PKR', 'Pakistani Rupee (Rs)'), ('BDT', 'Bangladeshi Taka (৳)'), ('LKR', 'Sri Lankan Rupee (Rs)'), ('NPR', 'Nepalese Rupee (Rs)'), ('MMK', 'Myanmar Kyat (K)'), ('KHR', 'Cambodian Riel (៛)'), ('LAK', 'Lao Kip (₭)')], default='INR', max_length=3),
        ),
    ]
